name: Deploy BTLP Wiki

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
        with:
          install-native: false
      - run: kotlin update_wiki.kts
      - name: Push BTLP Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: BungeeTabListPlus.wiki/
          GH_TOKEN: ${{ secrets.PAT }}
          GH_MAIL: ${{ secrets.MAIL }}
          GH_NAME: "CodeCrafter47"
          REPO: "CodeCrafter47/BungeeTabListPlus"